username:
  value: ilySHA
#?? ????????? postgres, ????? username.value

db:
  username: ${username.value:postgres}
  password: pass
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1
  pool:
    size: 12
    massiv:
      - 12
      - 13
      - 14
      - 15
    complex_massiv:
      - var1: 1
        var2: 2
        var3: 3
      - var1: 2
        var2: 3
        var3: 4

spring:
  profiles:
    active: prod