username:
  value: ilySHA

  # if we need to rename our properties in Class to camelCase,
  # we can wrote variables in kebab-case
db:
  # default postgres, if exist username.value, it will be written
  user-name: ${username.value:postgres}
  password: pass
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1
  pool:
    size: 12
    massiv:
      - 12
      - 13
      - 14
      - 15
    complex-massiv:
      - var1: 1
        var2: 2
        var3: 3
      - var1: 2
        var2: 3
        var3: 4

spring.profiles.active: prod

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: your_username
    password: your_password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate

# ONLY warn log messages will be showing on screen
logging:
  # pattern: - for unique logging
  level:
    # settings for all log Classes
    # OFF = disable
    root: INFO
    # set log hierarchy for classes/class on this way
    spring_ed.database: info
  file:
    # 10 mb MAX size, else will be created new file {file-name}+(FILE_NUMBER).log
    # myLog1.log, myLog2.log e.c.t.
    name: myLog.log
    path: /

